### ISSUE TITLE
Doesn't generate function docstrings on the following file

### ISSUE THREAD

**Issue by matt-lough** [matt-lough/solidity-docstring-generator#1]
Solidity Code:

```
pragma solidity ^0.4.18;

contract Migrations {
  address public owner;
  uint public last_completed_migration;

  modifier restricted() {
    if (msg.sender == owner) _;
  }

  function Migrations() public {
    owner = msg.sender;
  }

  function setCompleted(uint completed) public restricted {
    last_completed_migration = completed;
  }

  function upgrade(address new_address) public restricted {
    Migrations upgraded = Migrations(new_address);
    upgraded.setCompleted(last_completed_migration);
  }
}
```

Error message:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/mattbookpro/Library/Application Support/Sublime Text 3/Packages/SolidityDocstringGenerator/SolidityDocstringGenerator.py", line 208, in run
    self.process_file()
  File "/Users/mattbookpro/Library/Application Support/Sublime Text 3/Packages/SolidityDocstringGenerator/SolidityDocstringGenerator.py", line 168, in process_file
    self.insert_docstring(line_region)
  File "/Users/mattbookpro/Library/Application Support/Sublime Text 3/Packages/SolidityDocstringGenerator/SolidityDocstringGenerator.py", line 192, in insert_docstring
    docstring = construct_docstring(parse_declaration(line))
  File "/Users/mattbookpro/Library/Application Support/Sublime Text 3/Packages/SolidityDocstringGenerator/SolidityDocstringGenerator.py", line 134, in parse_declaration
    params.append(params_raw[i + 1])
IndexError: list index out of range
```

**Comment by matt-lough** [comment]
This one fixed it https://github.com/matt-lough/solidity-docstring-generator/commit/7b3febd054dbc3692bdf6303ec8d1dd9d23e0c1e
